export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCHED_INGREDIENTS_FAILED = "FETCHED_INGREDIENTS_FAILED";
export const PURCHASED_SUCCESS = "PURCHASED_SUCCESS";
export const PURCHASED_FAIL = "PURCHASED_FAIL";
